apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: ci
  labels:
    app: github-runner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: github-runner
        image: summerwind/actions-runner:latest
        env:
        - name: REPO_URL
          value: "https://github.com/Indeedelight12345/bitcoin-tradingapp"
        - name: RUNNER_NAME
          value: "github-runner"
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-runner
              key: token
